// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4t7EEV8ZMlSR392L-4rqLQdcvlWwrfug',
    appId: '1:91485155994:web:e1664595aa571f1460a523',
    messagingSenderId: '91485155994',
    projectId: 'soko-beauty-app',
    authDomain: 'soko-beauty-app.firebaseapp.com',
    storageBucket: 'soko-beauty-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhsaUk_bQimjzrkhEU5kNiN8uIYj_079I',
    appId: '1:91485155994:android:4e7b367cac1a5a1860a523',
    messagingSenderId: '91485155994',
    projectId: 'soko-beauty-app',
    storageBucket: 'soko-beauty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzQoIeaNzyHoRhJs-E53eqjfTC7OuUgxg',
    appId: '1:91485155994:ios:b956aa4b7109921e60a523',
    messagingSenderId: '91485155994',
    projectId: 'soko-beauty-app',
    storageBucket: 'soko-beauty-app.appspot.com',
    iosBundleId: 'com.example.sokoBeauty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzQoIeaNzyHoRhJs-E53eqjfTC7OuUgxg',
    appId: '1:91485155994:ios:9b1e02bf96a8728060a523',
    messagingSenderId: '91485155994',
    projectId: 'soko-beauty-app',
    storageBucket: 'soko-beauty-app.appspot.com',
    iosBundleId: 'com.example.sokoBeauty.RunnerTests',
  );
}
