// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7InV6kOYbNBBBdds1P-rF7JIP0X6-7WI',
    appId: '1:619847627673:web:81a0aa463d544a7e519908',
    messagingSenderId: '619847627673',
    projectId: 'sokobeauty-20bb2',
    authDomain: 'sokobeauty-20bb2.firebaseapp.com',
    storageBucket: 'sokobeauty-20bb2.appspot.com',
    measurementId: 'G-MQ9LMJ4K8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEs7rRT9s9624ZsBZgg9bZPMftuTjIEU',
    appId: '1:619847627673:android:944e560b3e0c715b519908',
    messagingSenderId: '619847627673',
    projectId: 'sokobeauty-20bb2',
    storageBucket: 'sokobeauty-20bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKiWyeji7BaepCXObCbBn77fw1AIwNplM',
    appId: '1:619847627673:ios:ec4c3e3fefdbb99f519908',
    messagingSenderId: '619847627673',
    projectId: 'sokobeauty-20bb2',
    storageBucket: 'sokobeauty-20bb2.appspot.com',
    iosBundleId: 'com.example.sokoBeauty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKiWyeji7BaepCXObCbBn77fw1AIwNplM',
    appId: '1:619847627673:ios:ebbaf61ca76d8900519908',
    messagingSenderId: '619847627673',
    projectId: 'sokobeauty-20bb2',
    storageBucket: 'sokobeauty-20bb2.appspot.com',
    iosBundleId: 'com.example.sokoBeauty.RunnerTests',
  );
}
